const visage = [
  '/:.````-/++syyhhhhddddhhhys/.`                                                                                                            ````````....---::://///////+++ooossssyyydmNNmdddddhhhhhdmmmmm',
  '::.`````-/+osyyyhhhyyyhhyso-.                    `````....`````...``....---.``                                            ``            ````````....---:////////////+oossssssyyyyydNNmmmmddhhhhhhmmmmmm',
  '.-.``````-/oossso+osyhyyso:.`                ``....--:::::::::::::////////////+/-..--::----:-.```````````````````````````````        ``````.......-:::/++++++++++oossyyyhhhhhhhhddmNmmmmmdhhhhhhhdmmmmm',
  '`--`  ```.-/osss++syyyyyo:.                   ``````..````..-:::/+++/////++oo++++osssyyyyyysso+//+/::/:-....----.....``````````````````....----::://+++osyyyhhhhhhdddmmmmmddmmmmmmmNNNmmddhhhhdhydmmmmm',
  '`...   ``.::///:-/+++sso/.`                        ```        ``....--::://+oooosssyyhhhyyyhhhhyyyysso+/::::///:::-....``````````````...---::/+ooosyyyhhddmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmdhhhhhhhydmmmmm',
  '-`..`  `.-:::-....-:+o+:.``                                        ```...-/+++oosyyyyhhhhyyhhhhhyyyyysooooo+o+++//:-..........`````..--::/oosyhhhdddmmmmmmmmNNNNNNNmmmmmddddddddhdmNNNmddhhhhhhhydmmmmm',
  's.```   `..---.....://:.`                            ````````````````...-----:::///++++oooooooosssssssssoooooo++///:-..............---::/syyhddmmmmmmmmmmmmddddhhhhhhhyyyhhhhhhhhdNNNNmdhhhhhhhhydmmmmm',
  'd+````   `..----.``.::.``                             ``.--::-----::///+oooossyyyyyysyyyyysssoo++/////:::/:::////:::--..........--:::/+oyyyhddmmmmmmmmmdddhhhhhyyyyyyyyyhhhhhhhhydNNNNmhhhhhhhhhydmmmmm',
  'mh-``.`    ``.::-` .--``                           ```..----::/+++ossyhhhooydmdhhddhyyyyyyyhhhhyso++/::----..----.............--::///ssyyhdddmmmNmmNNNNNNNNNmmmmmmmmmddddhhhhyhyydNNNNdhhhhhhhhhydmmmmm',
  'ddo`  `.`   `.-::.`...``                           ```..--::///++++++shhhsydmmmhhhhyo++syyyyyyyyyso+//:--.....````````````...-::/++osyhhddddddmmmddmNNNmmmmmmmdmmmmNNmmddhhhyyyyhmNNNmdhhhhhhhhhhdmmmmm',
  'ddy:   ```  `..:/-`````                              `````.--////:-```:oyyyhhhyyyys:..-:+oyysooooo+/:::-...`````        ```..-:/oosyhhddddddhyhdmddmNNmmddddhyyyhddmmmmmdhhyyyyyhmmmmmdhhhhhhhhhhdmmmmm',
  'ddho.         .-:-` ```                                   ```...````  `:syyyyyyyso-`..-:/osso+o+::-......````             ``.-:/syhhhhddddddhysyhdddddddddhsoosyyyhdddddhhyyyyyyhmmmmmdhhhhhhhhhhdmmmmm',
  'mmdh/`          ``` ```                                       ``````````.-/ooo+:.``..--:/+o+++/:-..```````                ``.-/syhhhhhhhhhhhhysssyhhhhhyso+/+osssyhddhhyyyyyyyyydNmmmmdhhhhhhhhhhdmmmmm',
  'mddd+`                                                          ``.......------.----::://++//:::-.```                      `.-/yyyyhyyyyyyyyyysssoooo++//++oossyyhhhyyyyyysyyyyymNmmmmdhhhhhhhhhhdmmmmm',
  'mdddo`                                                             ``...----:://////////////::::-.```                      `.-/yyyyyyyyyyyyyyyysssssssssssyyyyyyhyyyyyysssssyyyhmmmmmmdddhhhhhhhhdmmmmm',
  'mdddh/`                                                              ``````..--:::::::::::::----.```                       `.:syyyyyyyyysssssssssssssssssssyyyyyyyyyssssssssyyyhmdddmmddddhhhhhhhdmmmmm',
  'mmdddh/`                                                                    ```.......-..----...```                       ``.:syyyyyyyssssoooooo+++++++++oooossssssssssosssssyyhddddhdddddhhhhhhhdmmmmm',
  'mmddddh+.           ``                                                         `````````.....``                           ``.:ssssssssssoooooo+++///://////++ooooooooooooosssyhddddhhhhddddhhhhhydmmmmm',
  'mmmddddhy/.`        .-`     ``                                                  ````````````                              `..:+osssssooo++++++++////::::::://++ooooooooooosssyhdddhhhhhhhhhhhhhhydmmmmm',
  'mmmdddddhhhs/:-..-:+yh:     ``                                                   ````````                                 `..:+osssssoo+++///////////::::::////++++++++oooosyyhdhhhhhhhhhhhhhhhhydmmmmm',
  'mmmdddddddddddhdddmmmms`    ```                                                                                           ``.-/+ssssooo++///////:::///:::::////++++++++ooossyhddhhhhhhhhhhhhhhhhhdmmmmm',
  'dmmddddddddddddmmmNNNNh-     ```                                                                                           ``-:+osssooo+++///::::::::::::::://///++++++ooossyhdddhhhhhhhhhhhhhhhhmmmmmm',
  'dddmmdmmddddddddmNNNNNm/`      ``                                                                                         ```-:+osssoooo+++///::::::::::::::///////++++oossyhddddhhhhhhhhhhhhhhhhdmmmmm',
  'ddddmmmmddddmmddmNNNNNNs.       `                                                                                          ``-:+ossssooooo+///::::::--::::::://////++oosssyhmmddddhhhhhhhhhhhhhdhdmmmmm',
  'mddddmmmmmmmmmmddmNNNNNd:        ``                                                                                        `.-:+oosssooooo++//::::::::::::::///////+oosssyymNmdhddddhhhhhhhhhhhhhdmmmmm',
  'mmmmmmmmmmmmmmmmddmNNNNmo`       ``                                                                                       ``.-/+oosssssooo++//:::::::::::::://///++oossyyydNNNdddhddhhhhhhhhhhhhhdmmmmm',
  'mmmmmmmmmmmmmmmmmmmmNNNNh`                                                                                                ``.:/oosssssssoo++////::::::::::::////+oosssyyydNMNNmddddddhhhhhhhhhhhhdmmmmm',
  'mmNmmmmmmmmmmmmmmmdmmNNNm:                                                                                                 .-:/oosssssssso++////////::::://///+++oossyyydNMMMMNdddddddddhhhhhhhhhdmmmmm',
  'mNNNmmmmmmmmmmmmmmddmmNNNo`                                                                                               `.-:+oosssssssso++////////:::://///+++oosyyyhdNMMMMMNmddddhhhhhhhddhhhhdmmmmm',
  'NNNNmmmmmmmmmmmmmmmdmmmmNy-          `                                                                                    `.-/+ossssyysssoo+////////////////++oossyyyhmNMMMMMMNNmddddddddddddhhhhmmmmmN',
  'NNNNNNNmmmmmmmmmmmmmmmmmNd/                                                                                               `.-/+oosssyyyssoo++/////////////+++oossyyyhmNMMMMMMMMNNmddddddddddddddhmmmmmm',
  'NNNNNNNNNNmmmmmmmmmmmmmmNms`                                                                   ````                      ``.-/+oosssyyyysoo++///////////+++oossyyyyhmMMMMMMMMMNmmmmddddddhhhhdddhdmmmmm',
  'NNNNNNNNNNNmmmmmmmmmmmmmmmd.                                                                 ``````                      ``.-:/+oossyyyysoo++++///////++++oossyyyydNMMMMMMMMMNmddddddddddhhhhdddhdmmmmm',
  'NNNNNNNNNNNNNNNNNNNNNNmmmmm/``                                                           ``````````                     ````.-:/+oosyyyysoo+++++++++++++ooossyyyydNMMMMNMMMMMNdddddddddddddddddddmmmmmm',
  'NNNNNNNNNNNNNNNNNNNNNNNNNNNy.`                                                         ```````.`````                      ```.-:/+oosyyyssoo++++++++++ooosssyyyydNMMMMNNMMMMMNdddddddddddddddddddmmmmmm',
  'NNNNMNNNNNNNNNNNNNNNNNNNNNNd/``                                                      ````````.````                         ```.-:/+oosyysssoo++++++++ooossssyyyhmMMMMMMNMMMMNmdddddddddddddddddddmmmNNN',
  'NNNMMNNNNNNNNNNNNNMMNNNNNNNmh-`                                                      ``````..``                              `.--:/osyyssooooo+++ooooossssyyyydNNNMMMMNNMMMNmddddddddddddddddddddmNmmNN',
  'NNNNNNNNNNNNNNMMMMMMMMNNNNNNmo``                                                       ````..`                                `.-:/syyyssoooooooooooossssyyyydNNNNMMMMMMMMNmdddddddddddddddddddddmNmmNN',
  'NNNNNNNNNNNMMMMMMMMMMNNNNNNmmh:``                                                         `````      ``````              `````.-:/yyyyyssooooooooooossssyyyydNNNNNNMMMMMNNmddddddddddddddddddddddmmmNNN',
  'NNNNNNNNNMMMMMMMMMMMNNNNNNNmmmy.`                                                            ```...---......``        ```````-://syyyyssssoooooossssssyyyyydNNNNNNNNMMMMNNmddddddddddddddddddddddmNNNNN',
  'NNNNNNNNNMMMMMMMMMNNNNNNNNNmmmm/`                                                              ```.-::--------.`````````...-://ssyysssssssoooosssssssyyyyyhNMNNNNNNNMMMNNNmmmddddddddddddddddddddmNNNNN',
  'NNNNNNNNNNMMMMMMMNNNNNNNNNNNNmmd/`                                                               ```..-...-::::--...``..--:/osyyyyyyssssssoosssssssyyyyyyhmNMMNNNNNNNMMNNNNmmmmmdddddddddddddddddmNNNNN',
  'NNNNNNNNNNMMMMMNNNNNNNNNNNNNNNmmh:``                                                               ````..--:::///:::--::/osyyyyyyyyyyssssssssssssyyyyyyyhmNMMMMNNNNNNNNNNNNNNNmmmmmddddddddddddddmNNNNN',
  'NNNNNNNNNNNMMMNNNNNNNNNNNNNNNNNNmh:`                                                             ```````...--:://++o++ossyyyyyyyyyyyyysssssssssyyyyyyyyymNMMMMMNNNNNNNNNNNNNmmmmNNNmmmdddddddddddmNNNNM',
  'NNNNNNNNNMMMMNNNNNNNNNNNNNNNNNNNNNh-``                                                  ``   `` ``````````...-:/+oo++/++osyyyyysssssyyyyysssyyyyyyyyyyhdNMMMMMMMNmmmmNNNNNmmmmmdmmmmmmmmdddddddddNNNNMM',
]
export default visage
